name: Deploy dspace

on:
  push:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Ready script
      - name: Ready script
        run: chmod u+x $GITHUB_WORKSPACE/build-scripts/deploy-scripts/deploy.sh

      # change directory
      ## THIS IS PROBABLY WRONG WAY BUT I WANNA AVOID MULTILINE COMMANDS
      - name: change directory
        run: cd $GITHUB_WORKSPACE/build-scripts/deploy-scripts/

      - name: show directory
        run: pwd

      - name: list files
        run: ls -lsa

      - name: tree
        run: tree

      - name: list in deploy-scripts
        run: ls $GITHUB_WORKSPACE/build-scripts/deploy-scripts/

      # Runs script for deploy
      - name: Deploy attempt
        run: deploy.sh
