name: Deploy DSpace

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      - uses: actions/checkout@v3

      - name: deploy
        run: |
          cd $GITHUB_WORKSPACE/build-scripts/deploy-scripts/
          pwd

          touch .env || true
          echo DSPACE_REST_HOST=dev-5.pc > .env
          echo REST_URL=http://dev-5.pc:8080/server >> .env
          echo UI_URL=http://dev-5.pc >> .env
          echo DSPACE_REST_IMAGE=dataquest/dspace:dspace-7_x >> .env
          echo DOCKER_OWNER=dataquest >> .env
          echo NODE_ENV="development" >> .env

          ./deploy.sh
