name: Deploy dspace

on:
  push:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Ready script
      - name: Ready script
        run: chmod u+x $GITHUB_WORKSPACE/build-scripts/deploy-scripts/deploy.sh

      - name: change, list and run
        run: |
          cd $GITHUB_WORKSPACE/build-scripts/deploy-scripts/
          pwd
          ls -lsa
          ./deploy.sh

