name: Deploy dspace

on:
  push:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Ready script
      - name: Ready script
        run: chmod u+x $GITHUB_WORKSPACE/build-scripts/deploy-scripts/deploy.bat

      # Runs script for deploy
      - name: Deploy attempt
        run: $GITHUB_WORKSPACE/build-scripts/deploy-scripts/deploy.bat
