name: Deploy DSpace

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      - uses: actions/checkout@v3

      - name: deploy
        run: |
          cd $GITHUB_WORKSPACE/build-scripts/deploy-scripts/
          pwd

          export DSPACE_REST_HOST=dev-5.pc
          export REST_URL=http://dev-5.pc:8080/server
          export UI_URL=http://dev-5.pc/
          export DSPACE_REST_IMAGE=dataquest/dspace:dspace-7_x
          export DOCKER_OWNER=dataquest

          ./deploy.sh
