name: Deploy dspace

on:
  push:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Ready script
      - name: Ready script
        run: chmod u+x $GITHUB_WORKSPACE/build-scripts/deploy-scripts/deploy.sh

      # Runs script for deploy
      - name: Deploy attempt
        run: $GITHUB_WORKSPACE/build-scripts/deploy-scripts/deploy.sh
